name: Set up Windows environment
description: Set up everything needed to build and release things on Windows
inputs:
  architecture:
    description: The target architecture
    default: arm64
runs:
  using: composite
  steps:
    - name: Configure git
      run: |
        git config --global user.name "Shifttymike"
        git config --global user.email "github@atinyhedgehog.za.net"
      shell: pwsh
    - name: Check out releng
      run: |
        git submodule update --init --depth 1 releng
        cd releng
        git submodule update --init --depth 1
      shell: pwsh
    - name: Add convenience environment variables
      run: |
        echo "FRIDA_PREFIX=$Env:RUNNER_WORKSPACE\dist" >> $Env:GITHUB_ENV
        echo "FRIDA_VERSION=$(python releng/frida_version.py)" >> $Env:GITHUB_ENV
      shell: pwsh
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: ${{ inputs.architecture }}
    - name: Install setuptools
      run: pip install setuptools
      shell: pwsh
    - name: Install cloudflare-cli
      run: npm install -g cloudflare-cli
      shell: pwsh
